### ISSUE TITLE
Crash with GT6

### ISSUE THREAD

**Issue by unix-supremacist** [GTNewHorizons/ThaumicHorizons#46]
mod improperly assumes if the `gregtech` modid is loaded that gt5 is loaded, when gt6 and gt5 both share the same id

https://pastebin.com/9FPWYYiw

**Comment by Alastors** [comment]
> mod improperly assumes if the `gregtech` modid is loaded that gt5 is loaded, when gt6 and gt5 both share the same id
> 
> https://pastebin.com/9FPWYYiw

OOF, that's rough bud, I'll see what I can do when the coffee hits

**Comment by Yoghurt4C** [comment]
the simple solution would be to move the codeblock into a separate class along with imports to avoid interference and check `if (Loader.isModLoaded("gregtech") && !Loader.isModLoaded("gregapi")` before calling it

**Comment by Alastors** [comment]
> the simple solution would be to move the codeblock into a separate class along with imports to avoid interference and check `if (Loader.isModLoaded("gregtech") && !Loader.isModLoaded("gregapi")` before calling it

Yeah great, that's exactly what I'm going to do lmfaoooo, though I probably won't duplicate the support GT5 offers since I don't personally use 6

**Comment by SilearFlare** [comment]
hello yes hi you can fix with yogurtmethod yes good?

**Comment by SilearFlare** [comment]
ser
SER please SER
TWO MONTHS SER

**Comment by Alastors** [comment]
> ser
> 
> SER please SER
> 
> TWO MONTHS SER

> hello yes hi you can fix with yogurtmethod yes good? 

First off the "yoghurt method" means absolutely nothing to me.

Second off, I'm the only dev currently working on this mod, I just finished moving and came off hiatus, you don't need to be rude, I have multiple other mods I'm working on. Development in my free time can be slow at times.

**Comment by SilearFlare** [comment]
> the simple solution would be to move the codeblock into a separate class along with imports to avoid interference and check `if (Loader.isModLoaded("gregtech") && !Loader.isModLoaded("gregapi")` before calling it

's this thing

**Comment by Alastors** [comment]
> > the simple solution would be to move the codeblock into a separate class along with imports to avoid interference and check `if (Loader.isModLoaded("gregtech") && !Loader.isModLoaded("gregapi")` before calling it
> 
> 
> 
> 's this thing

Oh lmfao, thank you darling, yeah I'll look at it when I wake up, writing it down on my notepad now

**Comment by Rimusp** [comment]
As Magic bees does not have an Issues tab (or am i just dumb?) im asking here.
Gt6 crashes with magic bees and i think it might be a similar issue but as i dont have any idea of java i might be completely wrong lol

**Comment by thePalindrome** [comment]
Is anybody working on this, or should I do the PR, relearn the toolchain, and add in a simple version check?

(The number is in the mod info, you just have to check that it's 5 and not 6 for the major)

**Comment by GregoriusT** [comment]
Sorry for Past Greg being too stupid to change the darn Mod ID. XD

**Comment by thePalindrome** [comment]
> Sorry for Past Greg being too stupid to change the darn Mod ID. XD

Well, you updated the mod version number, so it works :P

**Comment by Abalieno** [comment]
As far as I know Thaumic Horizons loads fine with GT6.

Current incompatibilities are Thaumic Bases, EMT, Witching Gadgets, all for similar reasons.

**Comment by SilearFlare** [comment]
> As far as I know Thaumic Horizons loads fine with GT6.

That is technically correct, but also completely wrong. This is a crash pertaining the pocket plane option in ThaumicHorizons.cfg, which is, admittedly, disabled by default (although mostly for stability, it has actually been fleshed out and reworked extensively enough that it is a pretty interesting part of the mod in of itself):
`B:enablePocketPlane=false`
The moment you enable that option, it _will_ call for GT5 ores because they share the same ID, and it _will_ crash if you have gt6 installed. The solution to fix this is actually quite trivial, as it has been pointed out, stop calling `gregtech` and call `gregapi` instead.
