### ISSUE TITLE
Researches for Pocket Plane Content are disabled, but content is enabled

### ISSUE THREAD

**Issue by JohnsonJohnsonson** [GTNewHorizons/ThaumicHorizons#47]
Not sure if this is just a unique issue, but the researches don't show up, while the content itself still works:
![image](https://github.com/GTNewHorizons/ThaumicHorizons/assets/65741995/242caa73-eb7d-4b25-9b56-39c40e15e63f)
![image](https://github.com/GTNewHorizons/ThaumicHorizons/assets/65741995/14ff98d2-d6dd-4e91-8408-e0ff7ed54a44)

**Comment by JohnsonJohnsonson** [comment]
Addendum: Seems to affect versions 1.1.9.15 till 1.3.2

**Comment by Alastors** [comment]
shouldn't be a hard fix, I'll see what I can do

**Comment by DrParadox7** [comment]
The researches would only load if both `enablePocketPlane` is set to true and Gregtech is present.
Commit in question:
https://github.com/GTNewHorizons/ThaumicHorizons/pull/13/commits/4019d6e24f9e877fece443a3da163fdec48733a7

My latest PR should address that

**Comment by JohnsonJohnsonson** [comment]
Confirmed fixed on 1.3.4
![image](https://github.com/GTNewHorizons/ThaumicHorizons/assets/65741995/d1b49560-da50-409a-bb99-6642ee8d1b2c)
