### ISSUE TITLE
Pocket Planes are completely empty and cause you to fall into the Void

### ISSUE THREAD

**Issue by JohnsonJohnsonson** [GTNewHorizons/ThaumicHorizons#48]
Version affected:

Baubles: 1.0.1.10
Thaumcraft: 4.2.3.5
Thaumic Horizons: 1.3.2 (Curseforge Release)

Rundown of the Issue:

When creating a new Pocket Plane, it's completely empty, causing you to fall until you hit the void and die.

How to reproduce:

- Create new creative world
- Open Cheat Sheet Thaumonomicon
- Either find a Node or spawn one
- Either attenuate and transduce it or use a Node Opener
- Toss a Primal Pearl at it (notice how it takes very little time to "finish" the process
- Enter
- Die

**Comment by JohnsonJohnsonson** [comment]
Addendum: Seems to affect versions 1.3.0 till 1.3.2

**Comment by Alastors** [comment]
https://github.com/GTNewHorizons/ThaumicHorizons/pull/50 Fixed

**Comment by Shahelion** [comment]
This still happens with the creative Stable Vortex item, when it's used to create a pocket plane. Presumably because it has no aspects, since it was never a node. Maybe it should have some fallback default aspects?

**Comment by 5-Esania** [comment]
> This still happens with the creative Stable Vortex item, when it's used to create a pocket plane. Presumably because it has no aspects, since it was never a node. Maybe it should have some fallback default aspects?

(Tested on GTNH Daily 596)
I don't think that is the reason.
The creative stable vortex spawns with a few random aspects.
Trying to make a pocket plane often fails and just throws you into the void, and occasionally *crashes the game*.
Oddly, making pocket planes works much better when already inside of the pocket plane dimension. Issues and crashes still occasionally happen, although less frequently.
