### ISSUE TITLE
[Suggestion] Allow Automatic Insertion of Ethereal Essences into Ethereal Shards

### ISSUE THREAD

**Issue by lilpaladin1** [GTNewHorizons/ThaumicHorizons#74]
I was doing Blood Magic so I was killing a lot of Eldritch Guardians for LP. This caused me to amass thousands of Ethereal Essences. I thought I could insert said essences into the shard using automation, but no luck there.

I think it would be a great QoL change to allow pipes, conduits, hoppers, etc. to insert essences into the Ethereal Shard so I wouldn't have to deal with manually inserting like 3000 essences into a single shard.

**Comment by LazyFleshWasTaken** [comment]
YOu can insert them in using a dynamism tablet

**Comment by Alastors** [comment]
Rejected, there are already multiple ways to do this, Dynamism, Golems, etc.

**Comment by lilpaladin1** [comment]
I was not aware, noted.
