### ISSUE TITLE
Is there any way to enable generation of primordial fossils?

### ISSUE THREAD

**Issue by lueman** [GTNewHorizons/ThaumicHorizons#77]
I'm working on a modpack and primordial fossils are just perfect for my planed endgame but they are unobtainable. i saw there was some references to leviathanbones in PocketPlaneData.java so i was wondering if their generation was just disabled or incomplete. if they are just disabled, anyway to enable it?

**Comment by Alastors** [comment]
> I'm working on a modpack and primordial fossils are just perfect for my planed endgame but they are unobtainable. i saw there was some references to leviathanbones in PocketPlaneData.java so i was wondering if their generation was just disabled or incomplete. if they are just disabled, anyway to enable it?

Yeah so unfortunately its unfinished content from the original dev, I have his notes and have plans to finish it in the future but this is sadly not how it is at this current moment

**Comment by lueman** [comment]
Thats alright, I'll try and use Ore Tweaker to generate it as an ore. Thanks for the help. excited to see what comes of it
